package afcl.language.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FunctionBlock_Constraints extends BaseConstraintsDescriptor {
  public FunctionBlock_Constraints() {
    super(CONCEPTS.FunctionBlock$YY);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FunctionBlock$YY = MetaAdapterFactory.getConcept(0xec3060ee1f234e47L, 0xaf803618736238b3L, 0x658fbcf6b68e2599L, "afcl.language.structure.FunctionBlock");
  }
}
